import { Geist, Geist_Mono, Playfair_Display, Kalam, Kalam } from "next/font/google";
import SideBar from "@/components/Dashboard/SideBar";
import "../globals.css";
import Profile from "@/components/Dashboard/Profile";

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Add weights as needed
  variable: '--font-playfair',
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kalam = Kalam({
  variable: '--font-kalam',
  subsets: ["latin"],
  weight: ["400", "700"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
   return (
      <html lang="en" className={playfair.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kalam.variable}`}
      >
         <div className="h-screen flex dashboard-bg">
            {/* profile */}
            <Profile />

            {/* sidebar */}
            <SideBar />

            {/* main content */}
            <main className="grow overflow-y-auto">
               {children}
            </main>
         </div>
      </body>
    </html>
   )
}
