import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import SideBar from "@/components/Dashborad/SideBar";
import "../globals.css";

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Add weights as needed
  variable: '--font-playfair',
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
   return (
      <html lang="en" className={playfair.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#111111]`}
      >
         <div className="h-screen flex">
            <SideBar />
            <main className="grow overflow-y-auto">
               {children}
            </main>
         </div>
      </body>
    </html>
   )
}
